reattempt_script_on_failure
interactivereduction/autoreduction-scripts pull request #19
Opened 2023-07-28 08:11 UTC by keiranjprice101

Closes # 

## Description

2023-09-04 09:11 UTC, Pasarus approved these changes

2023-09-04 09:11 UTC, Pasarus requested changes
Did not mean to approve yet.

2023-09-05 10:23 UTC, keiranjprice101 commented on MARI/reduce.py
> +# Begin autoreduction inserted code
Ah that's true

2023-09-05 10:23 UTC, keiranjprice101 commented on MARI/reduce.py
> +# Begin autoreduction inserted code
I'll remove it

2023-09-15 09:05 UTC, Pasarus approved these changes

2023-09-15 09:05 UTC, merged